# Generated by Django 4.1.1 on 2022-09-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_mainapp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainapp',
            name='image',
            field=models.FilePathField(path='/img'),
        ),
    ]
